#!/usr/bin/env bun

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { generateKeyPairSync } from "node:crypto";

type OutputMode = "env" | "json";

function parseArgs(argv: string[]) {
  let outputMode: OutputMode = "env";
  let outputPath: string | null = null;
  let kid = `prod-${Date.now()}`;

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--json") {
      outputMode = "json";
      continue;
    }
    if (arg === "--env") {
      outputMode = "env";
      continue;
    }
    if (arg === "--write") {
      const next = argv[i + 1];
      if (!next) {
        throw new Error("Missing value for --write");
      }
      outputPath = next;
      i += 1;
      continue;
    }
    if (arg === "--kid") {
      const next = argv[i + 1];
      if (!next) {
        throw new Error("Missing value for --kid");
      }
      kid = next;
      i += 1;
      continue;
    }
    if (arg === "--help" || arg === "-h") {
      return { help: true as const };
    }
    throw new Error(`Unknown argument: ${arg}`);
  }

  return { help: false as const, kid, outputMode, outputPath };
}

function generateAuthKeys(kid: string) {
  const { privateKey, publicKey } = generateKeyPairSync("rsa", {
    modulusLength: 2048,
  });

  const privatePem = privateKey.export({ type: "pkcs8", format: "pem" }).toString();
  const publicJwk = publicKey.export({ format: "jwk" }) as JsonWebKey & {
    use?: string;
    alg?: string;
    kid?: string;
  };

  publicJwk.use = "sig";
  publicJwk.alg = "RS256";
  publicJwk.kid = kid;

  const jwks = JSON.stringify({ keys: [publicJwk] });

  return {
    JWT_PRIVATE_KEY: privatePem,
    JWKS: jwks,
  };
}

function formatEnvLine(key: string, value: string) {
  return `${key}=${JSON.stringify(value)}`;
}

function formatEnvFile(values: Record<string, string>) {
  const lines = [
    "# Generated by scripts/generate-convex-auth-keys.ts",
    "# Safe to keep out of git; rotate only if you want to invalidate existing sessions.",
    "",
  ];

  for (const key of Object.keys(values).sort()) {
    lines.push(formatEnvLine(key, values[key]));
  }

  return `${lines.join("\n")}\n`;
}

function printHelp() {
  console.log(`Generate Convex Auth signing keys.

Usage:
  bun scripts/generate-convex-auth-keys.ts [options]

Options:
  --env            Print .env-style output (default)
  --json           Print JSON output
  --write <path>   Write .env-style output to a file
  --kid <value>    Override the key id used in JWKS
  -h, --help       Show this help text
`);
}

async function main() {
  const parsed = parseArgs(Bun.argv.slice(2));
  if (parsed.help) {
    printHelp();
    return;
  }

  const keys = generateAuthKeys(parsed.kid);

  if (parsed.outputMode === "json") {
    const payload = JSON.stringify(keys, null, 2);
    if (parsed.outputPath) {
      const target = resolve(parsed.outputPath);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, `${payload}\n`, "utf8");
      return;
    }

    console.log(payload);
    return;
  }

  const content = formatEnvFile(keys);
  if (parsed.outputPath) {
    const target = resolve(parsed.outputPath);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content, "utf8");
    return;
  }

  process.stdout.write(content);
}

await main();
