#!/usr/bin/env bash

set -euo pipefail

ADMIN_KEY="${CONVEX_SELF_HOSTED_ADMIN_KEY:-}"
SELF_HOSTED_URL="http://127.0.0.1:3210"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env.local"
GENERATED_ENV_FILE="$REPO_ROOT/.env.self-hosted.local"
SKIP_DOCKER=0
SKIP_DEPLOY=0
SKIP_ENV_SYNC=0
START_FRONTEND=0
REGENERATE_ADMIN_KEY=0
REGENERATE_AUTH_KEYS=0
RESET_GENERATED_STATE=0
ADMIN_KEY_PROVIDED_EXPLICITLY=0

GENERATED_KEYS=(
  "CONVEX_SELF_HOSTED_ADMIN_KEY"
  "JWT_PRIVATE_KEY"
  "JWKS"
)

write_step() {
  printf '==> %s\n' "$1"
}

usage() {
  cat <<'EOF'
Usage: scripts/self-hosted-convex-up.sh [options]

Options:
  --admin-key <key>
  --self-hosted-url <url>
  --repo-root <path>
  --compose-dir <path>
  --env-file <path>
  --generated-env-file <path>
  --skip-docker
  --skip-deploy
  --skip-env-sync
  --start-frontend
  --regenerate-admin-key
  --regenerate-auth-keys
  --reset-generated-state
  -h, --help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --admin-key)
      ADMIN_KEY="${2:-}"
      ADMIN_KEY_PROVIDED_EXPLICITLY=1
      shift 2
      ;;
    --self-hosted-url)
      SELF_HOSTED_URL="${2:?missing value for --self-hosted-url}"
      shift 2
      ;;
    --repo-root)
      REPO_ROOT="${2:?missing value for --repo-root}"
      shift 2
      ;;
    --compose-dir)
      COMPOSE_DIR="${2:?missing value for --compose-dir}"
      shift 2
      ;;
    --env-file)
      ENV_FILE="${2:?missing value for --env-file}"
      shift 2
      ;;
    --generated-env-file)
      GENERATED_ENV_FILE="${2:?missing value for --generated-env-file}"
      shift 2
      ;;
    --skip-docker)
      SKIP_DOCKER=1
      shift
      ;;
    --skip-deploy)
      SKIP_DEPLOY=1
      shift
      ;;
    --skip-env-sync)
      SKIP_ENV_SYNC=1
      shift
      ;;
    --start-frontend)
      START_FRONTEND=1
      shift
      ;;
    --regenerate-admin-key)
      REGENERATE_ADMIN_KEY=1
      shift
      ;;
    --regenerate-auth-keys)
      REGENERATE_AUTH_KEYS=1
      shift
      ;;
    --reset-generated-state)
      RESET_GENERATED_STATE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

escape_env_value() {
  local value="$1"
  printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

emit_env_entry() {
  local key="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    return
  fi
  printf '%s="' "$key"
  escape_env_value "$value"
  printf '"\n'
}

write_generated_env_file() {
  local tmp
  tmp="$(mktemp)"
  {
    printf '# Generated by scripts/self-hosted-convex-up.sh\n'
    printf '# Safe to delete; the next self-hosted bootstrap can recreate these values.\n\n'
    emit_env_entry "CONVEX_SELF_HOSTED_ADMIN_KEY" "${CONVEX_SELF_HOSTED_ADMIN_KEY:-}"
    emit_env_entry "JWT_PRIVATE_KEY" "${JWT_PRIVATE_KEY:-}"
    emit_env_entry "JWKS" "${JWKS:-}"
  } >"$tmp"
  mv "$tmp" "$GENERATED_ENV_FILE"
}

load_env_file() {
  local path="$1"
  if [[ -f "$path" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$path"
    set +a
  fi
}

remove_dotenv_key() {
  local path="$1"
  local key="$2"
  if [[ ! -f "$path" ]]; then
    return
  fi

  awk -v target="$key" '
    BEGIN {
      skip = 0
      quote = ""
    }
    {
      if (skip) {
        if (quote != "" && $0 ~ quote "$") {
          skip = 0
          quote = ""
        }
        next
      }

      if (match($0, /^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*/, m)) {
        current = m[1]
        if (current == target) {
          remainder = substr($0, RLENGTH + 1)
          if (remainder ~ /^"/ && remainder !~ /"$/) {
            skip = 1
            quote = "\""
          } else if (remainder ~ /^'\''/ && remainder !~ /'\''$/) {
            skip = 1
            quote = "'\''"
          }
          next
        }
      }

      print
    }
  ' "$path" > "$path.tmp"

  mv "$path.tmp" "$path"
}

remove_dotenv_keys() {
  local path="$1"
  shift
  local key
  for key in "$@"; do
    remove_dotenv_key "$path" "$key"
  done
}

run_in_dir() {
  local workdir="$1"
  shift
  LAST_RUN_OUTPUT="$(
    cd "$workdir"
    "$@" 2>&1
  )"
  LAST_RUN_STATUS=$?
  if [[ -n "$LAST_RUN_OUTPUT" ]]; then
    printf '%s\n' "$LAST_RUN_OUTPUT"
  fi
  return "$LAST_RUN_STATUS"
}

run_checked() {
  local workdir="$1"
  shift
  if ! run_in_dir "$workdir" "$@"; then
    printf 'Command failed: %s\n' "$*" >&2
    return 1
  fi
}

get_generated_admin_key() {
  local output
  output="$(
    cd "$COMPOSE_DIR"
    docker compose exec -T backend ./generate_admin_key.sh 2>&1
  )"
  printf '%s\n' "$output"
  printf '%s\n' "$output" | grep -Eo 'convex-self-hosted\|[A-Za-z0-9]+' | tail -n 1
}

generate_auth_keys() {
  bun -e '
import { generateKeyPairSync } from "node:crypto";

const { privateKey, publicKey } = generateKeyPairSync("rsa", { modulusLength: 2048 });
const privatePem = privateKey.export({ type: "pkcs8", format: "pem" });
const publicJwk = publicKey.export({ format: "jwk" });
publicJwk.use = "sig";
publicJwk.alg = "RS256";
publicJwk.kid = `local-${Date.now()}`;
process.stdout.write(JSON.stringify({
  JWT_PRIVATE_KEY: privatePem,
  JWKS: JSON.stringify({ keys: [publicJwk] }),
}));
'
}

load_generated_auth_keys_from_json() {
  local json="$1"
  JWT_PRIVATE_KEY="$(printf '%s' "$json" | bun -e 'const input = await Bun.stdin.text(); const data = JSON.parse(input); process.stdout.write(data.JWT_PRIVATE_KEY);')"
  JWKS="$(printf '%s' "$json" | bun -e 'const input = await Bun.stdin.text(); const data = JSON.parse(input); process.stdout.write(data.JWKS);')"
}

set_resolved_admin_key() {
  local value="$1"
  if [[ -z "$value" ]]; then
    printf 'Cannot set an empty admin key.\n' >&2
    exit 1
  fi
  CONVEX_SELF_HOSTED_ADMIN_KEY="$value"
  export CONVEX_SELF_HOSTED_ADMIN_KEY
  export CONVEX_SELF_HOSTED_URL="$SELF_HOSTED_URL"
  write_generated_env_file
}

run_with_admin_key_refresh() {
  local label="$1"
  shift

  if run_checked "$REPO_ROOT" "$@"; then
    return 0
  fi

  if [[ "$ADMIN_KEY_PROVIDED_EXPLICITLY" -eq 0 && "${LAST_RUN_OUTPUT:-}" == *BadAdminKey* ]]; then
    write_step "Detected stale admin key while running $label; regenerating and retrying"
    local new_admin_key
    new_admin_key="$(get_generated_admin_key | tail -n 1)"
    set_resolved_admin_key "$new_admin_key"
    run_checked "$REPO_ROOT" "$@"
    return 0
  fi

  return 1
}

if [[ "$RESET_GENERATED_STATE" -eq 1 ]]; then
  write_step 'Resetting generated self-hosted state'
  rm -f "$GENERATED_ENV_FILE"
  remove_dotenv_keys "$ENV_FILE" "${GENERATED_KEYS[@]}"
fi

load_env_file "$GENERATED_ENV_FILE"
load_env_file "$ENV_FILE"

for generated_key in "${GENERATED_KEYS[@]}"; do
  if grep -q "^${generated_key}=" "$ENV_FILE" 2>/dev/null && [[ ! -f "$GENERATED_ENV_FILE" || ! $(grep -q "^${generated_key}=" "$GENERATED_ENV_FILE" 2>/dev/null; echo $?) -eq 0 ]]; then
    :
  fi
done

if [[ -f "$ENV_FILE" ]]; then
  for generated_key in "${GENERATED_KEYS[@]}"; do
    if grep -q "^${generated_key}=" "$ENV_FILE" 2>/dev/null; then
      case "$generated_key" in
        CONVEX_SELF_HOSTED_ADMIN_KEY) : "${CONVEX_SELF_HOSTED_ADMIN_KEY:=}" ;;
        JWT_PRIVATE_KEY) : "${JWT_PRIVATE_KEY:=}" ;;
        JWKS) : "${JWKS:=}" ;;
      esac
    fi
  done
fi

if [[ -f "$ENV_FILE" ]] && grep -Eq '^(CONVEX_SELF_HOSTED_ADMIN_KEY|JWT_PRIVATE_KEY|JWKS)=' "$ENV_FILE"; then
  write_step "Moving generated values from .env.local to $(basename "$GENERATED_ENV_FILE")"
  write_generated_env_file
  remove_dotenv_keys "$ENV_FILE" "${GENERATED_KEYS[@]}"
  load_env_file "$ENV_FILE"
fi

write_step "Using self-hosted Convex at $SELF_HOSTED_URL"

if [[ "$SKIP_DOCKER" -eq 0 ]]; then
  write_step "Starting Docker services from $COMPOSE_DIR"
  run_checked "$COMPOSE_DIR" docker compose up -d
fi

if [[ "$REGENERATE_ADMIN_KEY" -eq 1 || -z "${ADMIN_KEY:-}" ]]; then
  write_step 'Generating admin key from the running backend'
  ADMIN_KEY="$(get_generated_admin_key | tail -n 1)"
fi

set_resolved_admin_key "$ADMIN_KEY"

write_step 'Removing stale CONVEX_DEPLOYMENT from .env.local if present'
remove_dotenv_key "$ENV_FILE" 'CONVEX_DEPLOYMENT'

if [[ "$SKIP_DEPLOY" -eq 0 ]]; then
  write_step 'Deploying Convex functions to self-hosted backend'
  run_with_admin_key_refresh 'convex deploy' bunx convex deploy --typecheck=disable --yes
fi

if [[ "$REGENERATE_AUTH_KEYS" -eq 1 || -z "${JWT_PRIVATE_KEY:-}" || -z "${JWKS:-}" ]]; then
  write_step 'Generating local Convex Auth signing keys'
  auth_json="$(generate_auth_keys)"
  load_generated_auth_keys_from_json "$auth_json"
  write_generated_env_file
fi

load_env_file "$ENV_FILE"
load_env_file "$GENERATED_ENV_FILE"

if [[ "$SKIP_ENV_SYNC" -eq 0 ]]; then
  write_step 'Syncing backend runtime env vars from local env files'
  if [[ -n "${CONVEX_SITE_URL:-}" ]]; then
    printf 'Skipping CONVEX_SITE_URL: self-hosted Convex exposes this as a built-in value from the site proxy origin.\n'
  fi

  sync_keys=(
    "SITE_URL"
    "AUTH_GITHUB_ID"
    "AUTH_GITHUB_SECRET"
    "JWT_PRIVATE_KEY"
    "JWKS"
    "OPENAI_API_KEY"
  )

  for key in "${sync_keys[@]}"; do
    value="${!key:-}"
    if [[ -z "$value" ]]; then
      printf 'Skipping %s (empty)\n' "$key"
      continue
    fi

    printf 'Syncing %s\n' "$key"
    tmp_file="$(mktemp)"
    printf '%s' "$value" > "$tmp_file"
    run_checked "$REPO_ROOT" bunx convex env set "$key" --from-file "$tmp_file"
    rm -f "$tmp_file"
  done
fi

write_step 'Checking backend env access'
if ! run_with_admin_key_refresh 'convex env list' bunx convex env list; then
  printf 'Skipping `convex env list`: this self-hosted instance may not allow listing env vars with the current admin key.\n'
fi

printf 'Generated local self-hosted state file: %s\n' "$GENERATED_ENV_FILE"

if [[ "$START_FRONTEND" -eq 1 ]]; then
  write_step 'Starting frontend dev server'
  cd "$REPO_ROOT"
  exec bun run dev
fi

printf 'Self-hosted Convex bootstrap finished.\n'
