param(
  [string]$AdminKey,
  [string]$SelfHostedUrl = 'http://127.0.0.1:3210',
  [string]$RepoRoot = (Split-Path $PSScriptRoot -Parent),
  [string]$ComposeDir = (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),
  [string]$EnvFile = (Join-Path (Split-Path $PSScriptRoot -Parent) '.env.local'),
  [string]$GeneratedEnvFile = (Join-Path (Split-Path $PSScriptRoot -Parent) '.env.self-hosted.local'),
  [switch]$SkipDocker,
  [switch]$SkipDeploy,
  [switch]$SkipEnvSync,
  [switch]$StartFrontend,
  [switch]$RegenerateAdminKey,
  [switch]$RegenerateAuthKeys,
  [switch]$ResetGeneratedState
)

$ErrorActionPreference = 'Stop'

$generatedKeys = @(
  'CONVEX_SELF_HOSTED_ADMIN_KEY',
  'JWT_PRIVATE_KEY',
  'JWKS'
)

function Write-Step {
  param([string]$Message)
  Write-Host "==> $Message" -ForegroundColor Cyan
}

function Get-Utf8NoBomEncoding {
  return [System.Text.UTF8Encoding]::new($false)
}

function Unescape-DoubleQuotedEnvValue {
  param([string]$Value)

  $unescaped = $Value.Replace('\\', '\')
  $unescaped = $unescaped.Replace('\"', '"')
  $unescaped = $unescaped.Replace('\r', "`r")
  $unescaped = $unescaped.Replace('\n', "`n")
  $unescaped = $unescaped.Replace('\t', "`t")
  return $unescaped
}

function Parse-DotEnvFile {
  param([string]$Path)

  if (!(Test-Path -LiteralPath $Path)) {
    throw "Env file not found: $Path"
  }

  $result = @{}
  $lines = Get-Content -LiteralPath $Path

  for ($i = 0; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]
    if ($line -match '^\s*#' -or [string]::IsNullOrWhiteSpace($line)) {
      continue
    }
    if ($line -notmatch '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
      continue
    }

    $key = $matches[1]
    $value = $matches[2]

    if ($value.StartsWith('"')) {
      if ($value.Length -ge 2 -and $value.EndsWith('"')) {
        $value = $value.Substring(1, $value.Length - 2)
        $value = Unescape-DoubleQuotedEnvValue -Value $value
      } else {
        $parts = [System.Collections.Generic.List[string]]::new()
        $parts.Add($value.Substring(1))
        while (($i + 1) -lt $lines.Count) {
          $i += 1
          $next = $lines[$i]
          if ($next.EndsWith('"')) {
            $parts.Add($next.Substring(0, $next.Length - 1))
            break
          }
          $parts.Add($next)
        }
        $value = [string]::Join("`n", $parts)
        $value = Unescape-DoubleQuotedEnvValue -Value $value
      }
    } elseif ($value.StartsWith("'") -and $value.Length -ge 2 -and $value.EndsWith("'")) {
      $value = $value.Substring(1, $value.Length - 2)
    }

    $result[$key] = $value
  }

  return $result
}

function Read-DotEnvFileOrEmpty {
  param([string]$Path)

  if (!(Test-Path -LiteralPath $Path)) {
    return @{}
  }

  return Parse-DotEnvFile -Path $Path
}

function Format-DotEnvValue {
  param(
    [string]$Value,
    [switch]$RawJson
  )

  $normalized = $Value.Replace("`r`n", "`n").Replace("`r", "`n")
  if ($RawJson) {
    return "'$normalized'"
  }
  if ($normalized -match '^[A-Za-z0-9_./:-]+$') {
    return $normalized
  }

  $escaped = $normalized.Replace('\', '\\').Replace('"', '\"')
  return "`"$escaped`""
}

function Write-DotEnvFile {
  param(
    [string]$Path,
    [hashtable]$Values
  )

  if ($Values.Count -eq 0) {
    if (Test-Path -LiteralPath $Path) {
      Remove-Item -LiteralPath $Path -Force
    }
    return
  }

  $entries = [System.Collections.Generic.List[string]]::new()
  $entries.Add('# Generated by scripts/self-hosted-convex-up.ps1')
  $entries.Add('# Safe to delete; the next self-hosted bootstrap can recreate these values.')
  $entries.Add('')

  foreach ($key in ($Values.Keys | Sort-Object)) {
    $value = [string]$Values[$key]
    if ([string]::IsNullOrWhiteSpace($value)) {
      continue
    }
    $rawJson = $key -eq 'JWKS'
    $entries.Add("$key=$(Format-DotEnvValue -Value $value -RawJson:$rawJson)")
  }

  $content = [string]::Join("`n", $entries)
  [System.IO.File]::WriteAllText($Path, $content, (Get-Utf8NoBomEncoding))
}

function Remove-DotEnvKey {
  param(
    [string]$Path,
    [string]$Key
  )

  if (!(Test-Path -LiteralPath $Path)) {
    return
  }

  $lines = Get-Content -LiteralPath $Path
  $filtered = [System.Collections.Generic.List[string]]::new()
  $skipQuotedBlock = $false

  foreach ($line in $lines) {
    if ($skipQuotedBlock) {
      if ($line.EndsWith('"')) {
        $skipQuotedBlock = $false
      }
      continue
    }

    if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$' -and $matches[1] -eq $Key) {
      $value = $matches[2]
      if ($value.StartsWith('"') -and !($value.Length -ge 2 -and $value.EndsWith('"'))) {
        $skipQuotedBlock = $true
      }
      continue
    }

    $filtered.Add($line)
  }

  [System.IO.File]::WriteAllLines($Path, $filtered, (Get-Utf8NoBomEncoding))
}

function Remove-DotEnvKeys {
  param(
    [string]$Path,
    [string[]]$Keys
  )

  foreach ($key in $Keys) {
    Remove-DotEnvKey -Path $Path -Key $key
  }
}

function Format-ProcessArgument {
  param([string]$Argument)

  if ($null -eq $Argument) {
    return '""'
  }
  if ($Argument.Length -eq 0) {
    return '""'
  }
  if ($Argument -notmatch '[\s"]') {
    return $Argument
  }

  $builder = [System.Text.StringBuilder]::new()
  [void]$builder.Append('"')
  $backslashCount = 0

  foreach ($character in $Argument.ToCharArray()) {
    if ($character -eq '\') {
      $backslashCount += 1
      continue
    }

    if ($character -eq '"') {
      [void]$builder.Append('\', ($backslashCount * 2) + 1)
      [void]$builder.Append('"')
      $backslashCount = 0
      continue
    }

    if ($backslashCount -gt 0) {
      [void]$builder.Append('\', $backslashCount)
      $backslashCount = 0
    }

    [void]$builder.Append($character)
  }

  if ($backslashCount -gt 0) {
    [void]$builder.Append('\', $backslashCount * 2)
  }

  [void]$builder.Append('"')
  return $builder.ToString()
}

function Invoke-NativeProcess {
  param(
    [string]$FilePath,
    [string[]]$Arguments,
    [string]$WorkingDirectory
  )

  $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
  $startInfo.FileName = $FilePath
  $startInfo.WorkingDirectory = $WorkingDirectory
  $startInfo.RedirectStandardOutput = $true
  $startInfo.RedirectStandardError = $true
  $startInfo.UseShellExecute = $false

  $startInfo.Arguments = (($Arguments | ForEach-Object { Format-ProcessArgument -Argument $_ }) -join ' ')

  $process = [System.Diagnostics.Process]::new()
  $process.StartInfo = $startInfo

  try {
    if (!$process.Start()) {
      throw "Failed to start process: $FilePath"
    }
    $stdout = $process.StandardOutput.ReadToEnd()
    $stderr = $process.StandardError.ReadToEnd()
    $process.WaitForExit()
    return @{
      ExitCode = $process.ExitCode
      StdOut = $stdout
      StdErr = $stderr
    }
  } finally {
    $process.Dispose()
  }
}

function Split-ProcessOutput {
  param([string]$Value)

  if ([string]::IsNullOrEmpty($Value)) {
    return @()
  }
  return @($Value -split "\r?\n" | Where-Object { $_ -ne '' })
}

function Invoke-Checked {
  param(
    [string]$FilePath,
    [string[]]$Arguments,
    [string]$WorkingDirectory
  )

  $result = Invoke-NativeProcess -FilePath $FilePath -Arguments $Arguments -WorkingDirectory $WorkingDirectory
  $output = @(Split-ProcessOutput -Value $result.StdOut) + @(Split-ProcessOutput -Value $result.StdErr)

  foreach ($line in $output) {
    Write-Host $line
  }

  if ($result.ExitCode -ne 0) {
    $joined = ($output | ForEach-Object { $_.ToString() }) -join "`n"
    throw "Command failed: $FilePath $($Arguments -join ' ')`n$joined"
  }
}

function Invoke-Captured {
  param(
    [string]$FilePath,
    [string[]]$Arguments,
    [string]$WorkingDirectory
  )

  $result = Invoke-NativeProcess -FilePath $FilePath -Arguments $Arguments -WorkingDirectory $WorkingDirectory
  $output = @(Split-ProcessOutput -Value $result.StdOut) + @(Split-ProcessOutput -Value $result.StdErr)

  if ($result.ExitCode -ne 0) {
    $joined = ($output | ForEach-Object { $_.ToString() }) -join "`n"
    throw "Command failed: $FilePath $($Arguments -join ' ')`n$joined"
  }

  return [string[]]$output
}

function Set-ConvexEnvValue {
  param(
    [string]$Name,
    [string]$Value,
    [string]$WorkingDirectory
  )

  if ([string]::IsNullOrWhiteSpace($Value)) {
    Write-Host "Skipping $Name (empty)" -ForegroundColor DarkYellow
    return
  }

  Write-Host "Syncing $Name" -ForegroundColor Green
  $tempFile = New-TemporaryFile
  try {
    [System.IO.File]::WriteAllText($tempFile, $Value, (Get-Utf8NoBomEncoding))
    Invoke-Checked -FilePath 'bunx' -Arguments @('convex', 'env', 'set', $Name, '--from-file', $tempFile) -WorkingDirectory $WorkingDirectory
  } finally {
    Remove-Item -LiteralPath $tempFile -ErrorAction SilentlyContinue
  }
}

function Get-GeneratedAdminKey {
  param([string]$WorkingDirectory)

  Push-Location $WorkingDirectory
  try {
    $command = 'docker compose exec -T backend ./generate_admin_key.sh 2>&1'
    $output = cmd /c $command
    if ($LASTEXITCODE -ne 0) {
      $joined = ($output | ForEach-Object { $_.ToString() }) -join "`n"
      throw "Command failed: $command`n$joined"
    }
  } finally {
    Pop-Location
  }

  foreach ($line in [System.Linq.Enumerable]::Reverse([string[]]$output)) {
    if ($line -match 'convex-self-hosted\|[A-Za-z0-9]+') {
      return $matches[0]
    }
  }
  throw 'Could not parse admin key from `docker compose exec backend ./generate_admin_key.sh` output.'
}

function New-GeneratedAuthKeys {
  param([string]$WorkingDirectory)

  $script = @'
import { generateKeyPairSync } from 'node:crypto';

const { privateKey, publicKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
});

const privatePem = privateKey.export({ type: 'pkcs8', format: 'pem' });
const publicJwk = publicKey.export({ format: 'jwk' });
publicJwk.use = 'sig';
publicJwk.alg = 'RS256';
publicJwk.kid = `local-${Date.now()}`;

process.stdout.write(JSON.stringify({
  JWT_PRIVATE_KEY: privatePem,
  JWKS: JSON.stringify({ keys: [publicJwk] }),
}));
'@

  $output = Invoke-Captured -FilePath 'bun' -Arguments @('-e', $script) -WorkingDirectory $WorkingDirectory
  $json = ($output | ForEach-Object { $_.ToString() }) -join "`n"
  $parsed = $json | ConvertFrom-Json
  return @{
    JWT_PRIVATE_KEY = [string]$parsed.JWT_PRIVATE_KEY
    JWKS = [string]$parsed.JWKS
  }
}

function Merge-EnvMaps {
  param(
    [hashtable]$Primary,
    [hashtable]$Overlay
  )

  $merged = @{}
  foreach ($key in $Primary.Keys) {
    $merged[$key] = $Primary[$key]
  }
  foreach ($key in $Overlay.Keys) {
    $merged[$key] = $Overlay[$key]
  }
  return $merged
}

function Set-ResolvedAdminKey {
  param(
    [string]$Value,
    [hashtable]$GeneratedEnvMap,
    [string]$GeneratedEnvFilePath,
    [string]$SelfHostedBaseUrl
  )

  if ([string]::IsNullOrWhiteSpace($Value)) {
    throw 'Cannot set an empty admin key.'
  }

  $script:resolvedAdminKey = $Value
  $GeneratedEnvMap['CONVEX_SELF_HOSTED_ADMIN_KEY'] = $Value
  Write-DotEnvFile -Path $GeneratedEnvFilePath -Values $GeneratedEnvMap
  $env:CONVEX_SELF_HOSTED_URL = $SelfHostedBaseUrl
  $env:CONVEX_SELF_HOSTED_ADMIN_KEY = $Value
}

function Invoke-WithAdminKeyRefresh {
  param(
    [scriptblock]$Operation,
    [string]$FailureLabel,
    [bool]$CanRefreshAdminKey,
    [string]$ComposeWorkingDirectory,
    [hashtable]$GeneratedEnvMap,
    [string]$GeneratedEnvFilePath,
    [string]$SelfHostedBaseUrl
  )

  try {
    & $Operation
  } catch {
    $message = $_.Exception.Message
    if ($CanRefreshAdminKey -and $message -match 'BadAdminKey') {
      Write-Step "Detected stale admin key while running $FailureLabel; regenerating and retrying"
      $newAdminKey = Get-GeneratedAdminKey -WorkingDirectory $ComposeWorkingDirectory
      Set-ResolvedAdminKey -Value $newAdminKey -GeneratedEnvMap $GeneratedEnvMap -GeneratedEnvFilePath $GeneratedEnvFilePath -SelfHostedBaseUrl $SelfHostedBaseUrl
      & $Operation
      return
    }
    throw
  }
}

$repoEnvMap = Read-DotEnvFileOrEmpty -Path $EnvFile
$adminKeyProvidedExplicitly = ![string]::IsNullOrWhiteSpace($AdminKey)

if ($ResetGeneratedState) {
  Write-Step 'Resetting generated self-hosted state'
  if (Test-Path -LiteralPath $GeneratedEnvFile) {
    Remove-Item -LiteralPath $GeneratedEnvFile -Force
  }
  Remove-DotEnvKeys -Path $EnvFile -Keys $generatedKeys
}

$generatedEnvMap = Read-DotEnvFileOrEmpty -Path $GeneratedEnvFile
$migratedKeys = [System.Collections.Generic.List[string]]::new()
foreach ($key in $generatedKeys) {
  if (
    $repoEnvMap.ContainsKey($key) -and
    ![string]::IsNullOrWhiteSpace([string]$repoEnvMap[$key]) -and
    !$generatedEnvMap.ContainsKey($key)
  ) {
    $generatedEnvMap[$key] = [string]$repoEnvMap[$key]
    $migratedKeys.Add($key)
  }
}

if ($migratedKeys.Count -gt 0) {
  Write-Step "Moving generated values from .env.local to $(Split-Path $GeneratedEnvFile -Leaf)"
  Write-DotEnvFile -Path $GeneratedEnvFile -Values $generatedEnvMap
  Remove-DotEnvKeys -Path $EnvFile -Keys ([string[]]$migratedKeys)
  $repoEnvMap = Read-DotEnvFileOrEmpty -Path $EnvFile
}

Write-Step "Using self-hosted Convex at $SelfHostedUrl"

if (!$SkipDocker) {
  Write-Step "Starting Docker services from $ComposeDir"
  Invoke-Checked -FilePath 'docker' -Arguments @('compose', 'up', '-d') -WorkingDirectory $ComposeDir
}

$resolvedAdminKey = $AdminKey
if ([string]::IsNullOrWhiteSpace($resolvedAdminKey)) {
  $resolvedAdminKey = $env:CONVEX_SELF_HOSTED_ADMIN_KEY
}
if ([string]::IsNullOrWhiteSpace($resolvedAdminKey) -and $generatedEnvMap.ContainsKey('CONVEX_SELF_HOSTED_ADMIN_KEY')) {
  $resolvedAdminKey = [string]$generatedEnvMap['CONVEX_SELF_HOSTED_ADMIN_KEY']
}
if ($RegenerateAdminKey -or [string]::IsNullOrWhiteSpace($resolvedAdminKey)) {
  Write-Step 'Generating admin key from the running backend'
  $resolvedAdminKey = Get-GeneratedAdminKey -WorkingDirectory $ComposeDir
  $generatedEnvMap['CONVEX_SELF_HOSTED_ADMIN_KEY'] = $resolvedAdminKey
  Write-DotEnvFile -Path $GeneratedEnvFile -Values $generatedEnvMap
}

if ([string]::IsNullOrWhiteSpace($resolvedAdminKey)) {
  throw 'Admin key is required. Start Docker first, or pass -AdminKey explicitly.'
}

Set-ResolvedAdminKey -Value $resolvedAdminKey -GeneratedEnvMap $generatedEnvMap -GeneratedEnvFilePath $GeneratedEnvFile -SelfHostedBaseUrl $SelfHostedUrl

Write-Step 'Removing stale CONVEX_DEPLOYMENT from .env.local if present'
Remove-DotEnvKey -Path $EnvFile -Key 'CONVEX_DEPLOYMENT'

if (!$SkipDeploy) {
  Write-Step 'Deploying Convex functions to self-hosted backend'
  Invoke-WithAdminKeyRefresh `
    -FailureLabel 'convex deploy' `
    -CanRefreshAdminKey (-not $adminKeyProvidedExplicitly) `
    -ComposeWorkingDirectory $ComposeDir `
    -GeneratedEnvMap $generatedEnvMap `
    -GeneratedEnvFilePath $GeneratedEnvFile `
    -SelfHostedBaseUrl $SelfHostedUrl `
    -Operation {
      Invoke-Checked -FilePath 'bunx' -Arguments @('convex', 'deploy', '--typecheck=disable', '--yes') -WorkingDirectory $RepoRoot
    }
}

$generatedAuthMissing = @(
  'JWT_PRIVATE_KEY',
  'JWKS'
) | Where-Object {
  !$generatedEnvMap.ContainsKey($_) -or [string]::IsNullOrWhiteSpace([string]$generatedEnvMap[$_])
}

if ($RegenerateAuthKeys -or $generatedAuthMissing.Count -gt 0) {
  Write-Step 'Generating local Convex Auth signing keys'
  $generatedAuth = New-GeneratedAuthKeys -WorkingDirectory $RepoRoot
  $generatedEnvMap['JWT_PRIVATE_KEY'] = [string]$generatedAuth['JWT_PRIVATE_KEY']
  $generatedEnvMap['JWKS'] = [string]$generatedAuth['JWKS']
  Write-DotEnvFile -Path $GeneratedEnvFile -Values $generatedEnvMap
}

$envMap = Merge-EnvMaps -Primary $repoEnvMap -Overlay $generatedEnvMap

if (!$SkipEnvSync) {
  Write-Step 'Syncing backend runtime env vars from local env files'
  if ($envMap.ContainsKey('CONVEX_SITE_URL')) {
    Write-Host 'Skipping CONVEX_SITE_URL: self-hosted Convex exposes this as a built-in value from the site proxy origin.' -ForegroundColor DarkYellow
  }
  $keysToSync = @(
    'SITE_URL',
    'AUTH_GITHUB_ID',
    'AUTH_GITHUB_SECRET',
    'JWT_PRIVATE_KEY',
    'JWKS',
    'OPENAI_API_KEY'
  )

  foreach ($key in $keysToSync) {
    $value = if ($envMap.ContainsKey($key)) { [string]$envMap[$key] } else { '' }
    Set-ConvexEnvValue -Name $key -Value $value -WorkingDirectory $RepoRoot
  }
}

Write-Step 'Checking backend env access'
try {
  Invoke-WithAdminKeyRefresh `
    -FailureLabel 'convex env list' `
    -CanRefreshAdminKey (-not $adminKeyProvidedExplicitly) `
    -ComposeWorkingDirectory $ComposeDir `
    -GeneratedEnvMap $generatedEnvMap `
    -GeneratedEnvFilePath $GeneratedEnvFile `
    -SelfHostedBaseUrl $SelfHostedUrl `
    -Operation {
      Invoke-Checked -FilePath 'bunx' -Arguments @('convex', 'env', 'list') -WorkingDirectory $RepoRoot
    }
} catch {
  Write-Host 'Skipping `convex env list`: this self-hosted instance may not allow listing env vars with the current admin key.' -ForegroundColor DarkYellow
}

Write-Host "Generated local self-hosted state file: $GeneratedEnvFile" -ForegroundColor DarkGray

if ($StartFrontend) {
  Write-Step 'Starting frontend dev server'
  Push-Location $RepoRoot
  try {
    & bun run dev
  } finally {
    Pop-Location
  }
}

Write-Host 'Self-hosted Convex bootstrap finished.' -ForegroundColor Cyan
